### ISSUE TITLE
Hidden content visible without replying

### ISSUE THREAD

**Issue by 0xB9** [snlbaral/Hide-Thread-Content#1]
Hidden thread content is able to be viewed without replying by using the _reply_ or _quote_ button located in the postbit.

By clicking either two buttons you can view the thread content in the `[quote]` brackets without having to actually reply.
Example:
![example](https://user-images.githubusercontent.com/33612375/106061670-bc5c8000-60c3-11eb-90a0-b7c2799af071.png)

A solution would be to add a custom message inside the quote brackets for users who haven't replied that way thread content isn't revealed.
Example:
`[quote="admin" pid='17' dateline='1611782869']`
`Please reply to this thread to unlock the content.`
`[/quote]`

**Comment by snlbaral** [comment]
I've added custom quote message to resolve this issue. However there seems to be more ways of having a peak at the hidden post. I'll be working on that and release an update on mybb in a day or two.

**Comment by 0xB9** [comment]
Gotcha, a few other locations I just noticed were the portal page and by using the search, not sure if those are what you have already.

**Comment by snlbaral** [comment]
Yes. I'm working on those pages.

**Comment by Farman5482** [comment]
:
[quote="admin" pid='17' dateline='1611782869']
Please reply to this thread to unlock the content.
[/quote]
